"""
Domain models for Local File Organizer.

These models define the core data structures used throughout the pipeline:
- FileRecord: Scanned file with metadata
- Classification: LLM/Rule classification result
- PlanItem: Single action in execution plan
- ExecutionResult: Result of executing a PlanItem

All models use Pydantic for validation and serialization.
"""
from pathlib import Path
from datetime import datetime
from typing import Literal, Optional, Any
from pydantic import BaseModel, Field, field_validator, model_validator

# =============================================================================
# Constants
# =============================================================================

VALID_CATEGORIES = [
    "01_Trabalho",
    "02_Financas",
    "03_Estudos",
    "04_Livros",
    "05_Pessoal",
    "90_Inbox_Organizar"
]

VALID_ACTIONS = ["MOVE", "RENAME", "COPY", "SKIP"]

# Year range for validation
MIN_YEAR = 1900
MAX_YEAR = 2100


# =============================================================================
# FileRecord Model
# =============================================================================

class FileRecord(BaseModel):
    """
    Represents a scanned file with metadata.
    
    Created by the Scanner component after traversing directories.
    Contains all information needed for classification and planning.
    
    Attributes:
        path: Full path to the file
        size: File size in bytes (must be >= 0)
        mtime: Last modification time
        ctime: Creation time
        sha256: SHA256 hash of file contents
        extension: File extension (normalized to lowercase)
        mime: MIME type of the file (optional, set by Extractor)
        content_excerpt: Optional extracted content (max 8KB)
    """
    path: Path
    size: int = Field(ge=0, description="File size in bytes")
    mtime: datetime
    ctime: datetime
    sha256: Optional[str] = None
    extension: str
    mime: Optional[str] = None
    content_excerpt: Optional[str] = None
    
    model_config = {
        "arbitrary_types_allowed": True,
        "json_encoders": {
            Path: str,
            datetime: lambda v: v.isoformat()
        }
    }
    
    @field_validator('extension')
    @classmethod
    def normalize_extension(cls, v: str) -> str:
        """Normalize extension to lowercase."""
        return v.lower()


# =============================================================================
# Classification Model
# =============================================================================

class Classification(BaseModel):
    """
    LLM or Rule Engine classification result.
    
    Contains the category assignment and metadata for organizing a file.
    Used by the Planner to determine destination paths.
    
    Attributes:
        categoria: Target category (must be in VALID_CATEGORIES)
        subcategoria: Subcategory within the main category
        assunto: Brief description of the content
        ano: Year for organization (1900-2100)
        nome_sugerido: Suggested filename after organization
        confianca: Confidence score (0-100)
        racional: Explanation of the classification
    """
    categoria: str
    subcategoria: str
    assunto: str
    ano: int = Field(ge=MIN_YEAR, le=MAX_YEAR)
    nome_sugerido: str
    confianca: int = Field(ge=0, le=100)
    racional: str
    
    # Optional: rule_id if classified by rule engine
    rule_id: Optional[str] = None
    
    @field_validator('categoria')
    @classmethod
    def validate_categoria(cls, v: str) -> str:
        """Ensure categoria is one of the valid categories."""
        if v not in VALID_CATEGORIES:
            raise ValueError(
                f"categoria must be one of {VALID_CATEGORIES}, got '{v}'"
            )
        return v


# =============================================================================
# PlanItem Model
# =============================================================================

class PlanItem(BaseModel):
    """
    Single action in the execution plan.
    
    Represents one file operation to be executed (or skipped).
    Generated by the Planner component.
    
    IMPORTANT: DELETE is NOT a valid action. We NEVER delete files.
    
    Attributes:
        action: Operation type (MOVE, RENAME, COPY, SKIP)
        src: Source file path (required)
        dst: Destination path (None for SKIP)
        reason: Human-readable explanation
        confidence: Classification confidence (0-100)
        rule_id: ID of matching rule (if any)
        llm_used: Whether LLM was used for classification
    """
    action: Literal["MOVE", "RENAME", "COPY", "SKIP"]
    src: Path
    dst: Optional[Path] = None
    reason: str
    confidence: int = Field(ge=0, le=100)
    rule_id: Optional[str] = None
    llm_used: bool = False
    
    model_config = {
        "arbitrary_types_allowed": True,
        "json_encoders": {
            Path: str
        }
    }
    
    @model_validator(mode='after')
    def validate_dst_for_action(self) -> 'PlanItem':
        """Validate that non-SKIP actions have a destination."""
        if self.action != "SKIP" and self.dst is None:
            # Allow None dst for SKIP, warn for others
            pass  # We allow this for flexibility, planner should set dst
        return self


# =============================================================================
# ExecutionResult Model
# =============================================================================

class ExecutionResult(BaseModel):
    """
    Result of executing a PlanItem.
    
    Tracks the outcome of each file operation for the execution manifest.
    
    Attributes:
        status: Outcome (success, failed, skipped, dry-run)
        plan_item: The PlanItem that was executed
        error: Error message if status is 'failed'
        timestamp: When the execution occurred
    """
    status: Literal["success", "failed", "skipped", "dry-run"]
    plan_item: PlanItem
    error: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.now)
    
    model_config = {
        "arbitrary_types_allowed": True,
        "json_encoders": {
            Path: str,
            datetime: lambda v: v.isoformat()
        }
    }


# =============================================================================
# Export
# =============================================================================

__all__ = [
    "FileRecord",
    "Classification", 
    "PlanItem",
    "ExecutionResult",
    "VALID_CATEGORIES",
    "VALID_ACTIONS"
]
